/**
 * 额外纳管源
 *
 * 来源：ziyuanzu-cms-interfaces (1).json 的 73 源清单。
 * 规则：与当前 LunaTV-config 按归一化 API URL 去重后，仅保留未重复的 34 个源。
 *
 * 这里使用 JS manifest 而不是第二份 JSON 输出：
 * - 作为 02_process_lunatv_config.js 的输入扩展
 * - 仍然进入同一份 processed → 03 check → 04 convert 链路
 * - 最终只由 04 生成 OuonnkiTV/full.json 等统一 Registry
 */
module.exports = [
  {
    key: '360zy.com',
    name: '360资源站',
    api: 'https://360zy.com/api.php/provide/vod/',
    detail: 'https://360zy.com',
    isAdult: false,
  },
  {
    key: 'tyyszyapi.com',
    name: '天涯影视资源站',
    api: 'https://tyyszyapi.com/api.php/provide/vod/',
    detail: 'https://tyyszyapi.com',
    isAdult: false,
  },
  {
    key: 'haohuazy.com',
    name: '豪华资源站',
    api: 'https://haohuazy.com/api.php/provide/vod/',
    detail: 'https://haohuazy.com',
    isAdult: false,
  },
  {
    key: 'jipinvip1.com',
    name: '新极品资源站',
    api: 'https://jipinvip1.com/api.php/provide/vod/',
    detail: 'https://jipinvip1.com',
    isAdult: false,
  },
  {
    key: 'api.niuniuzy.me',
    name: '牛牛资源',
    api: 'https://api.niuniuzy.me/api.php/provide/vod/',
    detail: 'https://api.niuniuzy.me',
    isAdult: false,
  },
  {
    key: 'suonizy.net',
    name: '索尼采集站',
    api: 'https://suonizy.net/api.php/provide/vod/',
    detail: 'https://suonizy.net',
    isAdult: false,
  },
  {
    key: 'mtzy5.com',
    name: '茅台资源站',
    api: 'https://mtzy5.com/api.php/provide/vod/',
    detail: 'https://mtzy5.com',
    isAdult: false,
  },
  {
    key: 'huyazy.net',
    name: '虎牙资源站',
    api: 'https://huyazy.net/api.php/provide/vod/',
    detail: 'https://huyazy.net',
    isAdult: false,
  },
  {
    key: 'dbzy.tv',
    name: '豆瓣资源站',
    api: 'https://dbzy.tv/api.php/provide/vod/',
    detail: 'https://dbzy.tv',
    isAdult: false,
  },
  {
    key: 'subocj.com',
    name: '速播资源站',
    api: 'https://subocj.com/api.php/provide/vod/',
    detail: 'https://subocj.com',
    isAdult: false,
  },
  {
    key: 'www.suboziyuan.net',
    name: '速播资源站',
    api: 'https://www.suboziyuan.net/api.php/provide/vod/',
    detail: 'https://www.suboziyuan.net',
    isAdult: false,
  },
  {
    key: 'jyzyapi.com',
    name: '金鹰资源站',
    api: 'https://jyzyapi.com/provide/vod/',
    detail: 'https://jyzyapi.com',
    isAdult: false,
  },
  {
    key: 'ffzy5.tv',
    name: '非凡资源站',
    api: 'https://ffzy5.tv/api.php/provide/vod/',
    detail: 'https://ffzy5.tv',
    isAdult: false,
  },
  {
    key: 'dadiapi.com',
    name: '大地资源站',
    api: 'https://dadiapi.com/api.php',
    detail: 'https://dadiapi.com',
    isAdult: false,
  },
  {
    key: 'slapibf.com',
    name: '森林资源站',
    api: 'https://slapibf.com/api.php/provide/vod/',
    detail: 'https://slapibf.com',
    isAdult: true,
  },
  {
    key: 'xxavs.com',
    name: '湿乐园资源站',
    api: 'https://xxavs.com/api.php/provide/vod/',
    detail: 'https://xxavs.com',
    isAdult: true,
  },
  {
    key: 'fqzy.me',
    name: '番茄资源站',
    api: 'https://fqzy.me/api.php/provide/vod/',
    detail: 'https://fqzy.me',
    isAdult: false,
  },
  {
    key: 'bhziyuan.com',
    name: '百花资源站',
    api: 'https://bhziyuan.com/api.php/provide/vod',
    detail: 'https://bhziyuan.com',
    isAdult: false,
  },
  {
    key: 'caiji.semaozy.net',
    name: '色猫资源站',
    api: 'https://caiji.semaozy.net/inc/api.php',
    detail: 'https://caiji.semaozy.net',
    isAdult: true,
  },
  {
    key: 'api.vnzyz.com',
    name: '越南资源站',
    api: 'https://api.vnzyz.com/api.php/provide/vod/',
    detail: 'https://api.vnzyz.com',
    isAdult: false,
  },
  {
    key: 'hsckzy888.com',
    name: 'X色仓库资源',
    api: 'https://hsckzy888.com/api.php/provide/vod',
    detail: 'https://hsckzy888.com',
    isAdult: true,
  },
  {
    key: 'api.okzy.com',
    name: 'ok资源站',
    api: 'https://api.okzy.com/api.php/provide/vod',
    detail: 'https://api.okzy.com',
    isAdult: false,
  },
  {
    key: 'api.ukuzy.com',
    name: 'u酷资源站',
    api: 'https://api.ukuzy.com/api.php/provide/vod',
    detail: 'https://api.ukuzy.com',
    isAdult: false,
  },
  {
    key: 'api.yzzy.com',
    name: '优质资源站',
    api: 'https://api.yzzy.com/api.php/provide/vod',
    detail: 'https://api.yzzy.com',
    isAdult: false,
  },
  {
    key: 'api.ryzy.com',
    name: '如意资源站',
    api: 'https://api.ryzy.com/api.php/provide/vod',
    detail: 'https://api.ryzy.com',
    isAdult: false,
  },
  {
    key: 'api.kczy.com',
    name: '快车资源站',
    api: 'https://api.kczy.com/api.php/provide/vod',
    detail: 'https://api.kczy.com',
    isAdult: false,
  },
  {
    key: 'api.xlzy.com',
    name: '新浪资源站',
    api: 'https://api.xlzy.com/api.php/provide/vod',
    detail: 'https://api.xlzy.com',
    isAdult: false,
  },
  {
    key: 'api.hnzy2.com',
    name: '红牛资源站',
    api: 'https://api.hnzy2.com/api.php/provide/vod',
    detail: 'https://api.hnzy2.com',
    isAdult: false,
  },
  {
    key: 'api.jyzy.com',
    name: '金鹰资源站',
    api: 'https://api.jyzy.com/api.php/provide/vod',
    detail: 'https://api.jyzy.com',
    isAdult: false,
  },
  {
    key: 'api.sdzy.com',
    name: '闪电资源',
    api: 'https://api.sdzy.com/api.php/provide/vod',
    detail: 'https://api.sdzy.com',
    isAdult: false,
  },
  {
    key: 'api.yjzy.com',
    name: '雅集资源站',
    api: 'https://api.yjzy.com/api.php/provide/vod',
    detail: 'https://api.yjzy.com',
    isAdult: false,
  },
  {
    key: 'api.ckzy.com',
    name: 'ck资源站',
    api: 'https://api.ckzy.com/api.php/provide/vod',
    detail: 'https://api.ckzy.com',
    isAdult: false,
  },
  {
    key: 'www.xrbsp.com',
    name: '清水源资源站',
    api: 'https://www.xrbsp.com/api/json.php',
    detail: 'https://www.xrbsp.com',
    isAdult: false,
  },
  {
    key: 'www.gdlsp.com',
    name: '香系源资源站',
    api: 'https://www.gdlsp.com/api/json.php',
    detail: 'https://www.gdlsp.com',
    isAdult: false,
  },
];
